// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/12dac7db6491f9190af8585ece7e552c9a33ca96/systemjs/systemjs.d.ts
interface System {
  import(name: string): any;
  defined: any;
  amdDefine: () => void;
  amdRequire: () => void;
  baseURL: string;
  paths: { [key: string]: string };
  meta: { [key: string]: Object };
  config: any;
  _nodeRequire: (name: string) => any;
}

declare var System: System;

declare module "systemjs" {
  export = System;
}